<?php
/*
 * Generated configuration file
 * Generated by: phpMyAdmin 5.1.1 setup script
 * Date: Sat, 04 Sep 2021 12:27:18 +0000
 */

/* Servers configuration */
$i = 0;

/* Server: instadb [1] */
$i++;
$cfg['Servers'][$i]['verbose'] = 'instadb';
$cfg['Servers'][$i]['host'] = 'localhost';
$cfg['Servers'][$i]['port'] = '';
$cfg['Servers'][$i]['socket'] = '';
$cfg['Servers'][$i]['auth_type'] = 'cookie';
$cfg['Servers'][$i]['user'] = 'root';
$cfg['Servers'][$i]['password'] = '';

/* End of servers configuration */

$cfg['blowfish_secret'] = 'fx/ljsv@BXnqQZsHq"9+sQ>@?yTV';
$cfg['DefaultLang'] = 'en';
$cfg['ServerDefault'] = 1;
$cfg['UploadDir'] = '';
$cfg['SaveDir'] = '';
$cfg['Servers'][$i]['AllowNoPassword'] = TRUE;
?>
